# SPDX-License-Identifier: BSD-3-Clause
# Copyright Contributors to the OpenEXR Project.

name: OSS-Fuzz

# Skip the run on *.md changes and on changes to the website.
# Also, no need to run on changes to the bazel setup.

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'
      - '!src/wrappers/**'
      - '!.github/workflows/**'
      - '.github/workflows/ossfuzz_workflow.yml'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!website/**'
      - '!bazel/**'
      - '!src/wrappers/**'
      - '!.github/workflows/**'
      - '.github/workflows/ossfuzz_workflow.yml'
    # FIXME: Fuzzing build fails because we need to add libblosc2 to the list 
    # of linked libs in:
    # https://github.com/google/oss-fuzz/blob/master/projects/openexr/build.sh
    # ... but we can only do it once this PR is merged.
    branches-ignore:  # FIXME: REMOVE THIS CONDITION BEFORE MERGING !
      - 'main'

permissions:
  contents: read

jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@32f1d4deadc82279ec9001a837f2424e185c69a2 # master
      with:
        oss-fuzz-project-name: 'openexr'
        dry-run: false
        language: c++
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@32f1d4deadc82279ec9001a837f2424e185c69a2 # master
      with:
        oss-fuzz-project-name: 'openexr'
        fuzz-seconds: 300
        dry-run: false
        language: c++
    - name: Upload Crash
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
