# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.
#
# GitHub Actions workflow file
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Website

# Run only on changes in the "website" directory or workflow file.
# Skip the release branches, since the website is built from main.

on:

  push:
    branches-ignore:
      - RB-*
    paths:
      - 'website/**'
      - '.github/workflows/website_workflow.yml'
      
  pull_request:
    branches-ignore:
      - RB-*
    paths:
      - 'website/**'
      - '.github/workflows/website_workflow.yml'

permissions:
  contents: read

jobs:

  Website:

    # Build the website, using a process that mimics the readthedoc build.
    #
    # Note that this job does not actually build OpenEXR libraries or
    # programs, it just runs doxygen, sphinx, and the
    # website/script/test_images.py script to generate the "Test Images"
    # page.
    
    name: 'Website'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create build directory
        run: mkdir _build
      - name: Install doxygen & imagemagick
        # Need imagemagick for convert, to convert "Test Image" exrs to jpgs
        # Need openexr for exrheader
        run: sudo apt-get install -y doxygen imagemagick openexr 
      - name: Install sphinx requirements
        run: pip3 install -r website/requirements.txt
      - name: Configure
        run: cmake .. -DBUILD_WEBSITE='ON'
        working-directory: _build
      - name: Build
        run: |
          cmake --build . \
                --target website \
                --config Release
        working-directory: _build
    
