# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) Contributors to the OpenEXR Project.
#
# GitHub Actions workflow file
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Website

# Run only on changes in the "website" directory or workflow file.
# Skip the release branches, since the website is built from main.
#
# Readthedocs builds the website on ubuntu-20.04, so technically
# that's the only system that requires the website to build properly,
# but developers contributing to the website may work on Windows or
# macOS, so this confirms that it builds properly there, too.
#
# Note that this does not build the OpenEXR libraries, it only runs
# doxygen and sphinx to generate the website html.
#

on:

  push:
    branches-ignore:
      - RB-*
    paths:
      - 'website/**'
      - '.github/workflows/website.yml'
      
  pull_request:
    branches-ignore:
      - RB-*
    paths:
      - 'website/**'
      - '.github/workflows/website.yml'

permissions:
  contents: read

jobs:

  Website:

    name: "Website"

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
          
    env:
      # doxygen 1.10 causes sphinx to fail, so pin to 1.9 for now.
      DOXYGEN_VERSION: 1.9.1
      
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Create build directory
        run: mkdir _build
      - name: Install doxygen
        run: ./website/scripts/install_doxygen.sh ${DOXYGEN_VERSION} 
        shell: bash
      - name: Install sphinx requirements
        run: |
          python3 -m venv _venv
          source _venv/*/activate
          pip3 install -r ../website/requirements.txt
          cmake .. -DBUILD_WEBSITE=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DSPHINX_OPTS=""
        working-directory: _build
        shell: bash
      - name: Build
        run: |
          cmake --build . --target website --config Release
        working-directory: _build
        shell: bash
    
    
